# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(597, 505)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(60, 190, 461, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.write_tab = QtWidgets.QPushButton(self.widget)
        self.write_tab.setObjectName("write_tab")
        self.horizontalLayout_2.addWidget(self.write_tab)
        self.login_tab = QtWidgets.QPushButton(self.widget)
        self.login_tab.setObjectName("login_tab")
        self.horizontalLayout_2.addWidget(self.login_tab)
        self.read_tab = QtWidgets.QPushButton(self.widget)
        self.read_tab.setObjectName("read_tab")
        self.horizontalLayout_2.addWidget(self.read_tab)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.write_tab.setText(_translate("Form", "Write"))
        self.login_tab.setText(_translate("Form", "Login"))
        self.read_tab.setText(_translate("Form", "Read"))
