# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\desktop\app.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        self.main = QtWidgets.QTabWidget(Form)
        self.main.setGeometry(QtCore.QRect(0, 0, 500, 400))
        self.main.setObjectName("main")
        self.write = QtWidgets.QWidget()
        self.write.setObjectName("write")
        self.main.addTab(self.write, "")
        self.read = QtWidgets.QWidget()
        self.read.setObjectName("read")
        self.main.addTab(self.read, "")
        self.login = QtWidgets.QWidget()
        self.login.setObjectName("login")
        self.Login = QtWidgets.QPushButton(self.login)
        self.Login.setGeometry(QtCore.QRect(180, 210, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Login.setFont(font)
        self.Login.setObjectName("Login")
        self.widget = QtWidgets.QWidget(self.login)
        self.widget.setGeometry(QtCore.QRect(30, 77, 441, 81))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.password = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.main.addTab(self.login, "")

        self.retranslateUi(Form)
        self.main.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.main.setTabText(self.main.indexOf(self.write), _translate("Form", "Написать"))
        self.main.setTabText(self.main.indexOf(self.read), _translate("Form", "Читать"))
        self.Login.setText(_translate("Form", "Login"))
        self.label_2.setText(_translate("Form", "name"))
        self.label.setText(_translate("Form", "password"))
        self.main.setTabText(self.main.indexOf(self.login), _translate("Form", "Login"))
